services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "${NEXUS_PORT:-8081}:8081"
      - "${NEXUS_DOCKER_PORT:-8082}:8082"
    volumes:
      - nexus-data:/nexus-data
    environment:
      - NEXUS_JAVA_OPTS=-Djdbc.h2.DB_CLOSE_ON_EXIT=FALSE
    restart: always

volumes:
  nexus-data:
